-- 023: Daily Love Dares
-- One dare per couple per day, generated by a rotating AI judge persona.
-- Both partners submit encrypted responses; AI grades after both complete.

create table public.daily_dares (
  id                        uuid primary key default gen_random_uuid(),
  couple_id                 uuid not null references public.couples(id) on delete cascade,
  dare_date                 date not null default current_date,
  judge_persona             text not null,
  dare_text                 text not null,
  dare_category             text not null default 'playful',

  -- Partner A response (encrypted client-side)
  user_a_response_encrypted text,
  user_a_response_type      text default 'text',
  user_a_submitted_at       timestamptz,

  -- Partner B response (encrypted client-side)
  user_b_response_encrypted text,
  user_b_response_type      text default 'text',
  user_b_submitted_at       timestamptz,

  -- AI grading (populated after both submit)
  grade_commentary          text,
  grade_score               int,
  grade_emoji               text,
  grade_roast               text,
  graded_at                 timestamptz,

  -- Status lifecycle: pending → partial → complete → graded | expired
  status                    text not null default 'pending',
  expires_at                timestamptz not null default (current_date + interval '30 hours'),
  created_at                timestamptz not null default now(),

  constraint unique_couple_dare_date unique (couple_id, dare_date)
);

-- Indexes
create index idx_daily_dares_couple_date on public.daily_dares(couple_id, dare_date desc);
create index idx_daily_dares_active on public.daily_dares(status) where status in ('pending', 'partial');

-- RLS
alter table public.daily_dares enable row level security;

create policy "Users can view their couple dares"
  on public.daily_dares for select
  using (
    couple_id in (
      select id from public.couples
      where user_a_id = auth.uid() or user_b_id = auth.uid()
    )
  );

create policy "Users can insert dares for their couple"
  on public.daily_dares for insert
  with check (
    couple_id in (
      select id from public.couples
      where user_a_id = auth.uid() or user_b_id = auth.uid()
    )
  );

create policy "Users can update their couple dares"
  on public.daily_dares for update
  using (
    couple_id in (
      select id from public.couples
      where user_a_id = auth.uid() or user_b_id = auth.uid()
    )
  );

-- Add to Realtime publication so partner sees updates instantly
alter publication supabase_realtime add table public.daily_dares;
